version: '3'
services:
  nginx:
    image: helloz/nginx:alpine-1.24.0
    container_name: nginx
    #environment:
      
    network_mode: "host"
    volumes:
      - ../wwwroot:/var/www/html
      - ./data:/data/xcdn
      - ./logs:/data/logs
      - ./conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      
    restart:
      always