version: '3'
services:
  nginx:
    image: helloz/nginx:alpine-1.24.0
    container_name: nginx
    user: "${USER_ID}:${GROUP_ID}"
    #environment:
      
    network_mode: "host"
    volumes:
      - ../wwwroot:/var/www/html
      - ./conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./conf/vhost:/usr/local/nginx/conf/vhost
      - ./conf/stream:/usr/local/nginx/conf/stream
      - ./logs:/usr/local/nginx/logs
      - ./ssl:/usr/local/nginx/conf/ssl
      
    restart:
      always