version: '3.3'
services:
  mysql:
    image: mysql:8.2
    container_name: mysql8
    env_file: .env
    restart: always
    network_mode: host
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - './data:/var/lib/mysql'  
      - './my.cnf:/etc/mysql/my.cnf'